### ISSUE TITLE
npm install, and ng server with admin privileges is broken

### ISSUE THREAD

**Issue by ceballos59** [Aidurber/Ng2-ImgurClone#4]
(index):35 GET http://localhost:4200/vendor/angular2/bundles/angular2.dev.js 
(index):36 GET http://localhost:4200/vendor/angular2/bundles/http.dev.js 
(index):37 GET http://localhost:4200/vendor/angular2/bundles/router.dev.js 
(index):31 GET http://localhost:4200/vendor/angular2/bundles/angular2-polyfills.js 
(index):35 GET http://localhost:4200/vendor/angular2/bundles/angular2.dev.js 
(index):36 GET http://localhost:4200/vendor/angular2/bundles/http.dev.js 
(index):37 GET http://localhost:4200/vendor/angular2/bundles/router.dev.js 
system.src.js:1068 GET http://localhost:4200/angular2/platform/browser 404 (Not Found)fetchTextFromURL @ system.src.js:1068(anonymous function) @ system.src.js:1649n @ system-polyfills.js:4e @ system-polyfills.js:4(anonymous function) @ system.src.js:1648(anonymous function) @ system.src.js:2669(anonymous function) @ system.src.js:3233(anonymous function) @ system.src.js:3500(anonymous function) @ system.src.js:4116(anonymous function) @ system.src.js:4324(anonymous function) @ system.src.js:4564(anonymous function) @ system.src.js:326M @ system-polyfills.js:4H @ system-polyfills.js:4R.when @ system-polyfills.js:4b.run @ system-polyfills.js:4t._drain @ system-polyfills.js:4drain @ system-polyfills.js:4e @ system-polyfills.js:4
system.src.js:1068 GET http://localhost:4200/angular2/core 404 (Not Found)fetchTextFromURL @ system.src.js:1068(anonymous function) @ system.src.js:1649n @ system-polyfills.js:4e @ system-polyfills.js:4(anonymous function) @ system.src.js:1648(anonymous function) @ system.src.js:2669(anonymous function) @ system.src.js:3233(anonymous function) @ system.src.js:3500(anonymous function) @ system.src.js:4116(anonymous function) @ system.src.js:4324(anonymous function) @ system.src.js:4564(anonymous function) @ system.src.js:326M @ system-polyfills.js:4H @ system-polyfills.js:4R.when @ system-polyfills.js:4b.run @ system-polyfills.js:4t._drain @ system-polyfills.js:4drain @ system-polyfills.js:4e @ system-polyfills.js:4
system-polyfills.js:4 Potentially unhandled rejection [3] Error: XHR error (404 Not Found) loading http://localhost:4200/angular2/platform/browser
at error (http://localhost:4200/vendor/systemjs/dist/system.src.js:1026:16)
at XMLHttpRequest.xhr.onreadystatechange (http://localhost:4200/vendor/systemjs/dist/system.src.js:1047:13)(anonymous function) @ system-polyfills.js:4i @ system-polyfills.js:4s @ system-polyfills.js:4
system.src.js:1068 GET http://localhost:4200/angular2/core 404 (Not Found)fetchTextFromURL @ system.src.js:1068(anonymous function) @ system.src.js:1649n @ system-polyfills.js:4e @ system-polyfills.js:4(anonymous function) @ system.src.js:1648(anonymous function) @ system.src.js:2669(anonymous function) @ system.src.js:3233(anonymous function) @ system.src.js:3500(anonymous function) @ system.src.js:4116(anonymous function) @ system.src.js:4324(anonymous function) @ system.src.js:4564(anonymous function) @ system.src.js:326M @ system-polyfills.js:4H @ system-polyfills.js:4R.when @ system-polyfills.js:4b.run @ system-polyfills.js:4t._drain @ system-polyfills.js:4drain @ system-polyfills.js:4e @ system-polyfills.js:4
system.src.js:1068 GET http://localhost:4200/angular2/router 404 (Not Found)fetchTextFromURL @ system.src.js:1068(anonymous function) @ system.src.js:1649n @ system-polyfills.js:4e @ system-polyfills.js:4(anonymous function) @ system.src.js:1648(anonymous function) @ system.src.js:2669(anonymous function) @ system.src.js:3233(anonymous function) @ system.src.js:3500(anonymous function) @ system.src.js:4116(anonymous function) @ system.src.js:4324(anonymous function) @ system.src.js:4564(anonymous function) @ system.src.js:326M @ system-polyfills.js:4H @ system-polyfills.js:4R.when @ system-polyfills.js:4b.run @ system-polyfills.js:4t._drain @ system-polyfills.js:4drain @ system-polyfills.js:4e @ system-polyfills.js:4
system.src.js:1068 GET http://localhost:4200/angular2/http 404 (Not Found)fetchTextFromURL @ system.src.js:1068(anonymous function) @ system.src.js:1649n @ system-polyfills.js:4e @ system-polyfills.js:4(anonymous function) @ system.src.js:1648(anonymous function) @ system.src.js:2669(anonymous function) @ system.src.js:3233(anonymous function) @ system.src.js:3500(anonymous function) @ system.src.js:4116(anonymous function) @ system.src.js:4324(anonymous function) @ system.src.js:4564(anonymous function) @ system.src.js:326M @ system-polyfills.js:4H @ system-polyfills.js:4R.when @ system-polyfills.js:4b.run @ system-polyfills.js:4t._drain @ system-polyfills.js:4drain @ system-polyfills.js:4e @ system-polyfills.js:4
17system.src.js:291 Assertion failed: loading or loaded

**Comment by Aidurber** [comment]
@ceballos59 I've requested this project be removed from the Built with Angular 2 site since angular-cli had quite a few breaking changes from the time I developed this, until now. 

I added a note on the [README](https://github.com/Aidurber/Ng2-ImgurClone#important):

> Angular CLI went from v0.0.35 when I created to v1.0.0-beta1, so there are a few issues when trying to get ng CLI to play nice. I'm not sure whether it's worth adapting to all of the breaking changes.
> 
> I'm going to call this repo dead until further notice.

You might be able to try something like: 
```
npm install --save angular-cli@0.0.35 
```

Otherwise this project isn't going to have any more work done to it, I'm afraid. By all means, fork the project and make it your own if you wish.
